title: OpenShift on OCI Resource Attribution Tags - v1.4.1
description: A Terraform Stack for creating OpenShift Resource Attribution Tags.
schemaVersion: 1.4.1
version: "20251010"
locale: "en"

variableGroups:
  - title: "OpenShift Resource Attribution Tags"
    variables:
      - tenancy_ocid
      - tag_namespace_compartment_ocid_resource_tagging

###########
# VARIABLES
###########
variables:
  tenancy_ocid:
    title: Tenancy Ocid
    description: The ocid of the current tenancy.
    type: string
    default: tenancy_ocid
    required: true

  tag_namespace_compartment_ocid_resource_tagging:
    type: oci:identity:compartment:id
    title: Tag Namespace Compartment For OpenShift Resource Attribution Tags
    description: The compartment where the tag namespace for resource tags should be created. Defaults to current compartment. The tag namespace and defined tags for OpenShift Attribution on OCI resources will be `openshift-tags` and `openshift-resource`.
      If this namespace already exists, the field should be verified to ensure it is correctly defined and applied.
      Example --> "defined-tags" - {"openshift-tags"- {"openshift-resource" - "openshift-resource-infra"} }
    default: tenancy_ocid
    required: true
