#
# Copyright (c) 2019-2020 Oracle and/or its affiliates. All rights reserved.
#

title: OpenShift on OCI Tagging Resources
description: Terraform Stack for creating tagging resources
schemaVersion: 1.0.0
version: "20241019"
locale: "en"

variableGroups:
- title: "OpenShift Tagging Resources"
  variables:
  - tenancy_ocid
  - tag_namespace_name
  - tag_namespace_compartment_ocid

###########
# VARIABLES
###########
variables:
  tenancy_ocid:
    title: Tenancy Ocid
    description: The ocid of the current tenancy.
    type: string
    default: tenancy_ocid
    required: true

  tag_namespace_name:
    type: string
    title: Tag Namespace Name
    description: Name of tag namespace to create for tagging OpenShift OCI resources. WARNING - Tag namespace name must be unique accross the tenancy.
    default: ""
    required: true

  tag_namespace_compartment_ocid:
    type: oci:identity:compartment:id
    title: Tag Namespace Compartment
    description: Compartment to create tag namespace in. Defaults to current compartment.
    default: compartment_ocid
    required: true
