apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
  generation: 1
  name: csi-oci-node
  namespace: oci-csi
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: csi-oci-node
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: csi-oci-node
        role: csi-oci
    spec:
      containers:
        - name: oci-csi-node-driver
          args:
            - --v=2
            - --endpoint=unix:///csi/csi.sock
            - --nodeid=$(KUBE_NODE_NAME)
            - --loglevel=debug
            - --fss-endpoint=unix:///fss/csi.sock
          command:
            - /usr/local/bin/oci-csi-node-driver
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/host/usr/bin:/host/sbin
          image: ghcr.io/oracle/cloud-provider-oci:v1.25.0
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: plugin-dir
            - mountPath: /fss
              name: fss-plugin-dir
            - mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
              name: pods-mount-dir
            - mountPath: /dev
              name: device-dir
            - mountPath: /host
              name: host-root
            - mountPath: /sbin/iscsiadm
              name: chroot-iscsiadm
              subPath: iscsiadm
            - mountPath: /host/var/lib/kubelet
              mountPropagation: Bidirectional
              name: encrypt-pods-mount-dir
            - mountPath: /sbin/umount.oci-fss
              name: fss-driver-mounts
              subPath: umount.oci-fss
            - mountPath: /sbin/umount
              name: fss-driver-mounts
              subPath: umount
            - mountPath: /sbin/mount
              name: fss-driver-mounts
              subPath: mount
        - name: csi-node-registrar
          args:
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/blockvolume.csi.oraclecloud.com/csi.sock
          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.1
          securityContext:
            privileged: true
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - rm -rf /registration/blockvolume.csi.oraclecloud.com /registration/blockvolume.csi.oraclecloud.com-reg.sock
          volumeMounts:
            - mountPath: /csi
              name: plugin-dir
            - mountPath: /registration
              name: registration-dir
        - name: csi-node-registrar-fss
          args:
            - --csi-address=/fss/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/fss.csi.oraclecloud.com/csi.sock
          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
          securityContext:
            privileged: true
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - rm -rf /registration/fss.csi.oraclecloud.com /registration/fss.csi.oraclecloud.com-reg.sock
          volumeMounts:
            - mountPath: /fss
              name: fss-plugin-dir
            - mountPath: /registration
              name: registration-dir
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: csi-oci-node-sa
      serviceAccountName: csi-oci-node-sa
      terminationGracePeriodSeconds: 30
      tolerations:
        - operator: Exists
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: DirectoryOrCreate
          name: registration-dir
        - hostPath:
            path: /var/lib/kubelet/plugins/blockvolume.csi.oraclecloud.com
            type: DirectoryOrCreate
          name: plugin-dir
        - hostPath:
            path: /var/lib/kubelet/plugins/fss.csi.oraclecloud.com
            type: DirectoryOrCreate
          name: fss-plugin-dir
        - hostPath:
            path: /var/lib/kubelet
            type: Directory
          name: pods-mount-dir
        - hostPath:
            path: /var/lib/kubelet
            type: Directory
          name: encrypt-pods-mount-dir
        - hostPath:
            path: /dev
            type: ""
          name: device-dir
        - hostPath:
            path: /
            type: Directory
          name: host-root
        - configMap:
            name: oci-csi-iscsiadm
            defaultMode: 0755
          name: chroot-iscsiadm
        - configMap:
            name: oci-fss-csi
            defaultMode: 0755
          name: fss-driver-mounts
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
