# 10-autoscaling-operator-configs.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: oci-capi-operator-config
  namespace: oci-capi-operator
data:
  CAPI_VERSION: $CAPI_VERSION
  CAPOCI_VERSION: $CAPOCI_VERSION
  API_SERVER_LOAD_BALANCER_ID: $API_SERVER_LOAD_BALANCER_ID
  AUTOSCALER_CPUS: $AUTOSCALER_CPUS
  AUTOSCALER_DEFINED_TAGS_NAMESPACE: $AUTOSCALER_DEFINED_TAGS_NAMESPACE
  AUTOSCALER_MAX_NODES: $AUTOSCALER_MAX_NODES
  AUTOSCALER_MEMORY: $AUTOSCALER_MEMORY
  AUTOSCALER_MIN_NODES: $AUTOSCALER_MIN_NODES
  AUTOSCALER_SHAPE: $AUTOSCALER_SHAPE
  BARE_METAL_SUBNET_ID: $BARE_METAL_SUBNET_ID
  BARE_METAL_SUBNET_NAME: $BARE_METAL_SUBNET_NAME
  COMPARTMENT_ID: $COMPARTMENT_ID
  CONTROL_PLANE_ENDPOINT: $CONTROL_PLANE_ENDPOINT
  IMAGE_ID: $IMAGE_ID
  NETWORK_SECURITY_GROUP_ID: $NETWORK_SECURITY_GROUP_ID
  CLUSTER_NETWORK_CIDR_BLOCK: $CLUSTER_NETWORK_CIDR_BLOCK
  SERVICE_NETWORK_CIDR_BLOCK: $SERVICE_NETWORK_CIDR_BLOCK
  OCI_REGION: $OCI_REGION
  OCI_TENANCY_ID: $OCI_TENANCY_ID
  OCI_USE_INSTANCE_PRINCIPAL: $OCI_USE_INSTANCE_PRINCIPAL
  SUBNET_ID: $OCP_SUBNET_ID
  OCP_SUBNET_ID: $OCP_SUBNET_ID
  OCP_SUBNET_NAME: $OCP_SUBNET_NAME
  VCN_ID: $VCN_ID
---
