# This is a basic workflow to help you get started with Actions

name: Create Zip File

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "nikhsin/workflow-create-zip-file" ]
  pull_request:
    branches: [ "nikhsin/workflow-create-zip-file" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create_zip:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Install ZIP package
      - name: Install zip
        run: sudo apt-get install zip

      # Create ZIP file of the
      - name: Create ZIP file
        run: zip -r openshift-infrastructure.zip ./infrastructure.tf

      # Upload the zip file
      - name: Upload ZIP file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: repo-archive
          path: repo-archive.zip
